name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MoviesRecommend/requirements.txt
        pip install coverage unittest-xml-reporting
    - name: Debug information
      run: |
        cd MoviesRecommend
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo "Contents of Movie_recommendation_system directory:"
        ls -la Movie_recommendation_system
        echo "Contents of settings.py:"
        cat Movie_recommendation_system/settings.py
    - name: Create staticfiles directory
      run: |
        cd MoviesRecommend
        mkdir -p staticfiles
    - name: Run Tests
      run: |
        cd MoviesRecommend
        python manage.py test
    - name: Run Linting
      run: |
        pip install flake8
        flake8 . --max-line-length=120 --exclude=.git,__pycache__,docs/source/conf.py,old,build,dist,migrations --ignore=F401,E722,F841
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MoviesRecommend/requirements.txt
    - name: Create staticfiles directory
      run: |
        cd MoviesRecommend
        mkdir -p staticfiles
    - name: Collect Static Files
      run: |
        cd MoviesRecommend
        python manage.py collectstatic --noinput
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: MoviesRecommend/staticfiles
