name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage bandit


    - name: Run security checks
      run: bandit -r . -s B105,B110

    - name: Run Tests with Coverage
      run: |
        cd MoviesRecommend
        coverage run manage.py test
        coverage report

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

    - name: Run Tests
      run: |
        cd MoviesRecommend
        python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        - name: Deploy to production

        ssh user@your-server.com << EOF
          cd /path/to/your/project
    
          git pull origin main
    
    
          python manage.py migrate

          python manage.py collectstatic --noinput

          curl http://localhost:8000/health-check/
    
          echo "Deployment completed successfully!"
        EOF

    - name: Send notification
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment failed!
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
