name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Debug Information
      run: |
        echo "Current working directory:"
        pwd
        echo "Directory contents:"
        ls -R
        echo "Python version:"
        python --version
        echo "Pip version:"
        pip --version
        echo "Searching for manage.py:"
        find . -name manage.py

    - name: Run Tests
      run: |
        if [ -f manage.py ]; then
          python manage.py test
        else
          echo "manage.py not found in the current directory"
          MANAGE_PY_PATH=$(find . -name manage.py | head -n 1)
          if [ -n "$MANAGE_PY_PATH" ]; then
            echo "Found manage.py at: $MANAGE_PY_PATH"
            python $MANAGE_PY_PATH test
          else
            echo "manage.py not found in the project"
            exit 1
          fi
        fi
