name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pymysql
        if [ -f MoviesRecommend/requirements.txt ]; then
          pip install -r MoviesRecommend/requirements.txt
        else
          echo "requirements.txt not found, installing common dependencies"
          pip install django pymysql mysqlclient
        fi
    - name: Debug Information
      run: |
        echo "Current working directory:"
        pwd
        echo "Directory contents:"
        ls -R
        echo "Python version:"
        python --version
        echo "Pip version:"
        pip --version
        echo "Django version:"
        python -m django --version
        echo "Installed packages:"
        pip list
    - name: Run Tests
      run: |
        cd MoviesRecommend
        python manage.py test
    - name: Run Tests (alternative path)
      if: failure()
      run: |
        find . -name manage.py -exec python {} test \;
