name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Debug Information
      run: |
        pwd
        ls -la
        echo "Python version:"
        python --version
        echo "Pip version:"
        pip --version

    - name: Check manage.py
      run: |
        if [ -f manage.py ]; then
          echo "manage.py exists"
          cat manage.py
        else
          echo "manage.py does not exist"
          find . -name manage.py
        fi

    - name: Run Tests
      run: |
        python manage.py test

    - name: Run Tests (alternative path)
      if: failure()
      run: |
        find . -name manage.py -exec python {} test \;
